### ISSUE TITLE
unsigned Coordinater keeps crashing

### ISSUE THREAD

**Issue by Coollision** [schierlm/private-iota-testnet#15]
the coordinator keeps crashing with error [{"error":"Invalid trytes input","duration":12}] (see the full stack trace below)

any ideas on how to fix this?

I can do transactions, they confirm but after some time the coordinater always crashes....

I am using IRI version 1.4.2.2

jota.error.ArgumentException: [{"error":"Invalid trytes input","duration":12}]
	at jota.IotaAPICore.wrapCheckedException(IotaAPICore.java:71)
	at jota.IotaAPICore.storeTransactions(IotaAPICore.java:410)
	at iotatools.TestnetCoordinator.newMilestone(TestnetCoordinator.java:67)
	at iotatools.PeriodicCoordinator$1.run(PeriodicCoordinator.java:42)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:299)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)

**Comment by schierlm** [comment]
Since this error code is returned in a "catch all" exception handler inside `iri`, my suggestion would be to attach a debugger to iri (or to add some more logging statements [here](https://github.com/iotaledger/iri/blob/dev/src/main/java/com/iota/iri/service/API.java#L318)) and then have a look what problem iri has with the transaction. 

I am pretty sure that the reason is not any invalid trytes :-)

Regardless, the bug probably has to be fixed inside iri and not in the Coordinator...


(I've never seen it so far, but probably I've been lucky.)

**Comment by schierlm** [comment]
Closing due to lack of feedback. Feel free to reopen if needed.
