### ISSUE TITLE
iri crashes on testnet launch

### ISSUE THREAD

**Issue by ignasg** [schierlm/private-iota-testnet#24]
Tried latest and reference versions
```
C:\prj\iri-jar>java -jar iri-1.5.2.jar --testnet --testnet-no-coo-validation --s
napshot=Snapshot.txt -p 14700
Logging - property 'logging-level' set to: [INFO]
07/29 02:52:54.230 [main] WARN  com.iota.iri.IRI$IRILauncher - No neighbor has b
een specified. Server starting nodeless.
07/29 02:52:54.235 [main] INFO  com.iota.iri.IRI$IRILauncher - Welcome to IRI Te
stnet 1.5.2
Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\ai.ai-PC\App
Data\Local\Temp\librocksdbjni5296227579519074537.dll: ?ý*☻
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(Unknown Source)
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.load0(Unknown Source)
        at java.lang.System.load(Unknown Source)
        at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoade
r.java:78)
        at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:
56)
        at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:64)
        at org.rocksdb.RocksDB.<clinit>(RocksDB.java:35)
        at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.<init>(RocksD
BPersistenceProvider.java:28)
        at com.iota.iri.Iota.initializeTangle(Iota.java:189)
        at com.iota.iri.Iota.init(Iota.java:111)
        at com.iota.iri.IRI$IRILauncher.main(IRI.java:109)
        at com.iota.iri.IRI.main(IRI.java:32)
07/29 02:52:55.280 [Shutdown Hook] INFO  com.iota.iri.IRI$IRILauncher - Shutting
 down IOTA node, please hold tight...
07/29 02:53:01.287 [Shutdown Hook] ERROR com.iota.iri.IRI$IRILauncher - Exceptio
n occurred shutting down IOTA node:
java.lang.NullPointerException: null
        at com.iota.iri.network.replicator.ReplicatorSourcePool.shutdown(Replica
torSourcePool.java:73) ~[iri-1.5.2.jar:na]
        at com.iota.iri.network.replicator.Replicator.shutdown(Replicator.java:3
0) ~[iri-1.5.2.jar:na]
        at com.iota.iri.Iota.shutdown(Iota.java:163) ~[iri-1.5.2.jar:na]
        at com.iota.iri.IRI$IRILauncher.lambda$shutdownHook$0(IRI.java:371) ~[ir
i-1.5.2.jar:na]
        at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_171]

C:\prj\iri-jar>java -jar iri-1.4.2.4.jar --testnet --testnet-no-coo-validation -
-snapshot=Snapshot.txt -p 14700
07/29 02:55:24.853 [main] INFO  com.iota.iri.IRI - Welcome to IRI Testnet 1.4.2.
4
Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\ai.ai-PC\App
Data\Local\Temp\librocksdbjni7124913662758550453.dll: ?ýÉ☺
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(Unknown Source)
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.load0(Unknown Source)
        at java.lang.System.load(Unknown Source)
        at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoade
r.java:78)
        at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:
56)
        at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:64)
        at org.rocksdb.RocksDB.<clinit>(RocksDB.java:35)
        at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.<init>(RocksD
BPersistenceProvider.java:28)
        at com.iota.iri.Iota.initializeTangle(Iota.java:182)
        at com.iota.iri.Iota.init(Iota.java:104)
        at com.iota.iri.IRI.main(IRI.java:71)
07/29 02:55:26.159 [Shutdown Hook] INFO  com.iota.iri.IRI - Shutting down IOTA n
ode, please hold tight...
07/29 02:55:32.169 [Shutdown Hook] ERROR com.iota.iri.IRI - Exception occurred s
hutting down IOTA node:
java.lang.NullPointerException: null
        at com.iota.iri.network.replicator.ReplicatorSourcePool.shutdown(Replica
torSourcePool.java:73) ~[iri-1.4.2.4.jar:na]
        at com.iota.iri.network.replicator.Replicator.shutdown(Replicator.java:3
0) ~[iri-1.4.2.4.jar:na]
        at com.iota.iri.Iota.shutdown(Iota.java:156) ~[iri-1.4.2.4.jar:na]
        at com.iota.iri.IRI.lambda$shutdownHook$0(IRI.java:323) ~[iri-1.4.2.4.ja
r:na]
        at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_171]
```

Snapshot.txt
```
B9KMMIMKZ9RENTVPEXJTMQBFH9PDNGYVCUINMHWODWVCHCLAPVDDMXFEVLNER9JTGBEJURSVOPFQKIZXY;2779530283277761
```

Snapshot.log
```
Generating new Snapshot.txt file...
Enter amounts to be stored on the given addresses.
Amounts can be given as numbers, or with suffixes Ki Mi Gi Ti Pi.
Hit Return without entering an amount to switch to another seed.
Hit return for the first address of a seed assign the remaining IOTA
and finish the process.

Remaining IOTA: 2779530283277761

Seed: JEIMKVNATISFUMKBUHQHBPGQHGRXCYVJFKPHYEICYEGVPF9WBDDAMLSBABQQBNSXGCSMVUDPYNKPAAWVT
  B9KMMIMKZ9RENTVPEXJTMQBFH9PDNGYVCUINMHWODWVCHCLAPVDDMXFEVLNER9JTGBEJURSVOPFQKIZXYMKVG9DBYY: 
  B9KMMIMKZ9RENTVPEXJTMQBFH9PDNGYVCUINMHWODWVCHCLAPVDDMXFEVLNER9JTGBEJURSVOPFQKIZXYMKVG9DBYY: 2779530283277761

Done.
```
No ini file was created

**Comment by schierlm** [comment]
The error does not look like it could be caused by running a private testnet, more like some DLL incompatibility on your system.

Does iri start on your machine when you try running the official testnet or the mainnet?

If not, you should check that the Java version you are using is indeed 64-bit (rocksdb does not include 32-bit binaries for Windows) and that you have the latest 64-bit VC redistributable installed (from Microsoft).

If that does not help, please open a bug at [upstream iri](https://github.com/iotaledger/iri/issues) project.

Alternatively, if possible you can try running it on Linux (e.g. a VM). Most productive iri nodes ar running on Linux so it is much better tested there.
