### ISSUE TITLE
First Coordinator run throws java.lang.RuntimeException: Invalid transaction hash

### ISSUE THREAD

**Issue by vikulin** [schierlm/private-iota-testnet#8]
IRI throws:
12/29 17:41:54.324 [XNIO-1 task-6] ERROR com.iota.iri.service.API - API Exception: 
java.lang.RuntimeException: Invalid transaction hash
	at com.iota.iri.TransactionValidator.runValidation(TransactionValidator.java:89) ~[iri-1.4.1.2.jar:na]
	at com.iota.iri.TransactionValidator.validate(TransactionValidator.java:95) ~[iri-1.4.1.2.jar:na]
	at com.iota.iri.service.API.attachToTangleStatement(API.java:782) [iri-1.4.1.2.jar:na]
	at com.iota.iri.service.API.process(API.java:212) [iri-1.4.1.2.jar:na]
	at com.iota.iri.service.API.processRequest(API.java:172) [iri-1.4.1.2.jar:na]
	at com.iota.iri.service.API.access$000(API.java:82) [iri-1.4.1.2.jar:na]
	at com.iota.iri.service.API$1.handleRequest(API.java:153) [iri-1.4.1.2.jar:na]
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:208) [iri-1.4.1.2.jar:na]
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:809) [iri-1.4.1.2.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]

~ java -jar iota-testnet-tools-0.1-SNAPSHOT-jar-with-dependencies.jar Coordinator localhost 14265
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.IllegalAccessError: 500 {"exception":"Invalid transaction hash","duration":2184}
	at jota.IotaAPICore.wrapCheckedException(IotaAPICore.java:79)
	at jota.IotaAPICore.attachToTangle(IotaAPICore.java:377)
	at iotatools.TestnetCoordinator.newMilestone(TestnetCoordinator.java:60)
	at iotatools.TestnetCoordinator.main(TestnetCoordinator.java:38)
	at iotatools.Main.main(Main.java:16)

**it looks like following condition failed:**
class com.iota.iri.TransactionValidator
        if(weightMagnitude < minWeightMagnitude) {
            /*
            log.error("Hash found: {}", transactionViewModel.getHash());
            log.error("Transaction trytes: "+Converter.trytes(transactionViewModel.trits()));
            */
            throw new RuntimeException("Invalid transaction hash");
        }

**Comment by schierlm** [comment]
Coordinator will use MWM=13, which is usually enough for testnet. If the minimum weight magnitude of your node is higher, feel free to [patch the source](https://github.com/schierlm/private-iota-testnet/blob/master/src/main/java/iotatools/TestnetCoordinator.java#L60) accordingly.
